### PR TITLE
Randomised colour of food

### PR DESCRIPTION
**Pull request by SarenCurrie**
Not sure if the randomColor function should be part of the game object. Also, used US spelling for consistency, programming is racist against people who speak proper English.

### CODE REVIEW

**Comment by SarenCurrie** [comment]
Also changed chat commands and added dark mode and help commands.

**Comment by SarenCurrie** [comment]
If you want to test out these changes: http://agar.sarencurrie.com:3000

**Comment by matthewAURA** [comment]
Kind of feel that we should just say fuck it, spell properly, but whatever

**Comment by matthewAURA** [comment]
I'm going to set up Jenkins properly to build PR's soon + your sever is down so when I can test I will then merge :)

**Comment by SarenCurrie** [comment]
~~@matthewAURA mind testing it locally? I'm not sure what's going on with my server right now.~~

**Comment by SarenCurrie** [comment]
Never mind, it's back up now.

**Comment by matthewAURA** [comment]
Looks good :shipit:

**Pull request merged**
