### PR TITLE
Add Tommy's eating fix.

### PR DESCRIPTION
**Pull request by SarenCurrie**

### CODE REVIEW

**Comment by matthewAURA** [comment]
Setting up Jenkins to build PR's now

**Comment by matthewAURA** [comment]
test this please

**Comment by matthewAURA** [comment]
test this please

**Comment by matthewAURA** [comment]
test this please

**Comment by matthewAURA** [comment]
test this please

**Comment by matthewAURA** [comment]
test this please

**Comment by matthewAURA** [comment]
test this please

**Comment by matthewAURA** [comment]
Jenkins y you do this

**Comment by matthewAURA** [comment]
test this please

**Comment by matthewAURA** [comment]
test this please

**Comment by SarenCurrie** [comment]
Well it works _better,_ but it still doesn't really work properly.

**Comment by matthewAURA** [comment]
Oh, "test this please" was the message to jenkins to clone the PR and build it, but if you did then that's cool too

**Comment by SarenCurrie** [comment]
Ah, that would explain why I got an email notification about that about ten times.

**Comment by matthewAURA** [comment]
This looks good but your last commit (b3680f) broke it

**Pull request closed without merging**
